version: '2'

# ------------------------------
# Named networks within the docker-compose app
# We are dividing up the network into public and private subnets
# to seperate out the public interfaces from the internal services, such as the database, redis cache, etc.
# ------------------------------
# networks:
#   - front-tier
#   - back-tier


# ------------------------------
# Volumes to attach to the project
# ------------------------------
# volumes:
#   db-data:


# ------------------------------
# Services within the project
# There are two public docker images: redis & postgres
# and three private docker contexts: worker, api, and web
# ------------------------------
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    # networks:
    #   - back-tier

  db:
    image: postgres:alpine
    container_name: db
    ports: ["5432"]
    # networks:
    #   - back-tier
    volumes:
      - "./db-data:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  worker:
    build: ./worker
    # networks:
    #   - back-tier

  api:
    build: ./web-api
    container_name: 'api'
    ports:
      - "5000:80"
    volumes:
      - ./web-api:/app
    # networks:
    #   - front-tier
    #   - back-tier

  web:
    build: ./web-frontend
    container_name: 'frontend'
    ports:
      - "5001:80"
      - "5858:5858"
    volumes:
      - ./web-frontend:/app
    # networks:
    #   - front-tier
    #   - back-tier
